export enum TakumiPayError {
  NotOwner = 6000,
  NotAdminOrOwner = 6001,
  ContractPaused = 6002,
  PointDepositsPaused = 6003,
  ZeroAddress = 6004,
  ZeroAmount = 6005,
  AlreadyOwner = 6006,
  NotPendingOwner = 6007,
  NoPendingTransfer = 6008,
  QuoteExpired = 6009,
  RefConsumed = 6010,
  BadQuote = 6011,
  FeeExceedsAmount = 6012,
  FeeAmountInvalid = 6013,
  ZeroSigner = 6014,
  ZeroRecipient = 6015,
  AmountExceedsLimit = 6016,
  TimelockActive = 6017,
  InsufficientBalance = 6018,
  DelayExceedsMax = 6019,
  NoDelaySet = 6020,
  TimelockNotExpired = 6021,
  AlreadyExecuted = 6022,
  AlreadyCancelled = 6023,
  TokenNotAllowed = 6024,
  InvalidStringLength = 6025,
  InvalidRefIdHash = 6026,
  MissingEd25519Instruction = 6027,
  InvalidEd25519Instruction = 6028,
  WithdrawalTypeMismatch = 6029,
  Overflow = 6030,
}

export const TAKUMI_PAY_ERROR_MESSAGES: Record<TakumiPayError, string> = {
  [TakumiPayError.NotOwner]: "Not the contract owner",
  [TakumiPayError.NotAdminOrOwner]: "Not an admin or owner",
  [TakumiPayError.ContractPaused]: "Contract is paused",
  [TakumiPayError.PointDepositsPaused]: "Point deposits are paused",
  [TakumiPayError.ZeroAddress]: "Zero address not allowed",
  [TakumiPayError.ZeroAmount]: "Amount must be greater than zero",
  [TakumiPayError.AlreadyOwner]: "Already the owner",
  [TakumiPayError.NotPendingOwner]: "Not the pending owner",
  [TakumiPayError.NoPendingTransfer]: "No pending ownership transfer",
  [TakumiPayError.QuoteExpired]: "Quote has expired",
  [TakumiPayError.RefConsumed]: "Reference ID already consumed",
  [TakumiPayError.BadQuote]: "Invalid quote signature",
  [TakumiPayError.FeeExceedsAmount]: "Platform fee exceeds payment amount",
  [TakumiPayError.FeeAmountInvalid]: "Fee amount invalid",
  [TakumiPayError.ZeroSigner]: "Backend signer cannot be zero",
  [TakumiPayError.ZeroRecipient]: "Recipient cannot be zero",
  [TakumiPayError.AmountExceedsLimit]: "Amount exceeds spending limit",
  [TakumiPayError.TimelockActive]: "Timelock is active, use queue/execute",
  [TakumiPayError.InsufficientBalance]: "Insufficient balance",
  [TakumiPayError.DelayExceedsMax]: "Withdrawal delay exceeds maximum",
  [TakumiPayError.NoDelaySet]: "Withdrawal delay must be set before queuing",
  [TakumiPayError.TimelockNotExpired]: "Withdrawal timelock not yet expired",
  [TakumiPayError.AlreadyExecuted]: "Withdrawal already executed",
  [TakumiPayError.AlreadyCancelled]: "Withdrawal already cancelled",
  [TakumiPayError.TokenNotAllowed]: "Token not allowed for point deposits",
  [TakumiPayError.InvalidStringLength]: "Invalid string length",
  [TakumiPayError.InvalidRefIdHash]: "Ref ID hash mismatch",
  [TakumiPayError.MissingEd25519Instruction]:
    "Missing Ed25519 signature instruction",
  [TakumiPayError.InvalidEd25519Instruction]:
    "Invalid Ed25519 instruction data",
  [TakumiPayError.WithdrawalTypeMismatch]: "Withdrawal type mismatch",
  [TakumiPayError.Overflow]: "Arithmetic overflow",
};
