/**
 * `WalletKitAdapter` — first-party wallet docking port.
 *
 * Mirrors the `ChainAdapter` pattern (see `services/chains/types.ts`), but
 * covers first-party mobile wallet operations that are NOT dApp-originated:
 * keypair creation / import, address validation, native balance fetch,
 * native send, MAX-amount calculation, human/raw amount formatting.
 *
 * Every namespace (`eip155`, `solana`, …) implements this interface and
 * registers itself via `walletKitRegistry` so that UI code (`app/send.tsx`,
 * `app/wallet.tsx`, add-wallet sheets, …) can stay namespace-agnostic.
 *
 * Rules (enforced by spec §4.5 + Task 04):
 *   - No `react` / `react-native` imports — this module must run under a
 *     Node test harness.
 *   - No `viem` imports — viem lives inside `services/walletKit/evm/` only.
 */

import type {
  AddressLookupTableAccount,
  PublicKey,
  Signer,
  TransactionInstruction,
} from "@solana/web3.js";
import type { TBlockchain } from "@/api/types/blockchain";
import type { ChainConfig } from "@/constants/configs/chainConfig";
import type { TWallet } from "@/constants/types/walletTypes";
import type { Namespace } from "@/services/chains/types";

export type { Namespace };

/**
 * Arguments for `WalletKitAdapter.signTransferWithAuthorization` — the
 * EIP-3009 `TransferWithAuthorization` primitive Circle Nanopayments
 * accepts. EVM-only; Solana kit leaves the method `undefined`.
 *
 * Crucial detail (spec §5.5): the EIP-712 domain points at Circle's
 * `GatewayWallet` contract on the source chain — NOT the USDC contract.
 * `{ gatewayWallet, domainName, domainVersion }` arrive pre-fetched via
 * `GET /gateway/v1/x402/supported` at backend boot and are piped through
 * `PaymentIntent.nanopay.domain`. Signing against the USDC contract's
 * domain will pass `/gateway/v1/x402/verify` but fail settle — don't.
 *
 * The adapter does NOT broadcast. Submission is the caller's job.
 */
export interface SignTransferWithAuthorizationArgs {
  wallet: TWallet;
  chain: ChainConfig;
  /** EIP-712 `verifyingContract` — the Gateway batched-wallet contract. */
  gatewayWallet: `0x${string}`;
  /** e.g. `"GatewayWalletBatched"` — from `/gateway/v1/x402/supported`. */
  domainName: string;
  /** e.g. `"1"` — from `/gateway/v1/x402/supported`. */
  domainVersion: string;
  /** USDC asset address — embedded in the `TransferWithAuthorization` struct. */
  usdc: `0x${string}`;
  from: `0x${string}`;
  to: `0x${string}`;
  /** 6-decimal USDC units. */
  valueMicros: bigint;
  /** Unix seconds; usually 0. */
  validAfter: number;
  /**
   * Unix seconds. MUST be `≥ now + 3 days` or Gateway rejects with
   * `authorization_validity_too_short`. Adapter enforces this guard
   * pre-sign so the UX can surface a typed error before the keystore
   * is touched.
   */
  validBefore: number;
  /** 32-byte random, generated by the server. */
  nonce: `0x${string}`;
}

/**
 * Minimum signer validity window Circle Gateway enforces — 3 days in
 * unix seconds. Exported so tests and callers can reference the same
 * constant instead of re-deriving it.
 */
export const GATEWAY_VALID_BEFORE_MIN_SECONDS = 259_200;

/**
 * Typed error thrown by `signTransferWithAuthorization` when the
 * incoming `validBefore` is below `now + 3 days`. Screens should catch
 * by `name === "AuthorizationValidityTooShortError"` and map to a UX
 * string without re-parsing the message.
 */
export class AuthorizationValidityTooShortError extends Error {
  readonly name = "AuthorizationValidityTooShortError";
  readonly validBefore: number;
  readonly minimumValidBefore: number;
  constructor(args: { validBefore: number; minimumValidBefore: number }) {
    super(
      `validBefore (${args.validBefore}) is below the Gateway minimum (${args.minimumValidBefore}); ` +
        `Circle requires validBefore ≥ now + 3 days.`,
    );
    this.validBefore = args.validBefore;
    this.minimumValidBefore = args.minimumValidBefore;
  }
}

/**
 * Arguments for `WalletKitAdapter.signX402SvmPayment` — the Solana
 * counterpart to `signTransferWithAuthorization` for the Path B-SVM rail
 * (spec §5.2.1, §5.5, milestone M6). Solana-only; EVM kits leave this
 * `undefined`. Consumers presence-check rather than branching on
 * `namespace === "solana"`.
 *
 * Unlike EIP-3009 (where the signer produces a 65-byte typed-data
 * signature the backend stuffs into an on-chain call), the SVM x402
 * scheme hands the wallet a *pre-built* base64-encoded versioned
 * transaction. The facilitator is the `feePayer` — it has already
 * authored the ComputeBudget / TransferChecked / (optional) Memo
 * instructions per §5.2.1 wire format. The wallet adds its own
 * signature over the message bytes and returns the updated base64 tx;
 * the facilitator later attaches the `feePayer` signature and submits
 * to the network (task 43).
 *
 * Rules the adapter enforces:
 *   - Instruction list is immutable. The facilitator's settle path
 *     rejects any tx whose message bytes differ from what it issued.
 *   - The adapter adds the *user's* signature only — the fee-payer slot
 *     is left untouched (still the caller-supplied placeholder / null).
 *   - No broadcast. Submission is the backend's job (memory:
 *     `feedback_role_separation.md`).
 */
export interface SignX402SvmPaymentArgs {
  wallet: TWallet;
  /** Cluster discriminator carried through to the facilitator POST. */
  cluster: "mainnet-beta" | "devnet";
  /**
   * Base64-encoded versioned Solana transaction, partially signed with
   * a `feePayer` placeholder per §5.2.1. The wallet adds the user's
   * signature and returns the updated base64 blob.
   */
  transaction: string;
}

/**
 * Typed error thrown by `signX402SvmPayment` when the wallet's declared
 * namespace does not match `"solana"`. Separate from the kit-level
 * assert so UI can catch it by `name === "SvmWalletNamespaceMismatchError"`
 * and surface a dedicated string instead of a generic "wrong chain".
 */
export class SvmWalletNamespaceMismatchError extends Error {
  readonly name = "SvmWalletNamespaceMismatchError";
  readonly walletNamespace: string;
  constructor(walletNamespace: string) {
    super(
      `signX402SvmPayment: expected solana wallet, got namespace=${walletNamespace}`,
    );
    this.walletNamespace = walletNamespace;
  }
}

/**
 * Typed error thrown by `signX402SvmPayment` when the wallet has no
 * Solana signer (no keypair materialisable from `expo-secure-store`).
 * Separate error so UX can hint "re-import / re-create wallet" instead
 * of swallowing the generic failure.
 */
export class SvmSignerUnavailableError extends Error {
  readonly name = "SvmSignerUnavailableError";
  readonly walletAddress: string;
  constructor(walletAddress: string) {
    super(`signX402SvmPayment: no Solana signer for wallet ${walletAddress}`);
    this.walletAddress = walletAddress;
  }
}

/**
 * Arguments for `WalletKitAdapter.sendUserOpWithUsdcPaymaster` — the
 * ERC-4337 UserOperation primitive that lets Circle Paymaster pay gas
 * in USDC on Base / Arbitrum (spec §5.4 gasless table, §5.5 adapter
 * surface, §12 Q6 ERC-4337 / EIP-7702 path).
 *
 * The adapter builds a UserOp with a two-call batch: an `approve` on
 * USDC so the paymaster can pull gas funds, and the actual target call
 * (e.g. `GatewayWallet.deposit`). If the wallet is a plain EOA, the
 * adapter attaches an EIP-7702 `authorization` so Entry-Point v0.8
 * treats the EOA as a `Simple7702Account`.
 *
 * `chainId` / Circle Paymaster chain-gating is the **caller's** job —
 * the adapter does not validate the chain against Circle's allowlist
 * (Base / Arbitrum in v1; may expand). Passing an unsupported chainId
 * will result in a bundler 4xx at submit time.
 *
 * EVM-only; Solana kit leaves the method `undefined`. Consumers
 * dispatch via presence-of-method rather than `if (namespace === ...)`.
 */
export interface SendUserOpWithUsdcPaymasterArgs {
  wallet: TWallet;
  chain: ChainConfig;
  /** Target contract being called (e.g. `GatewayWallet` for a deposit). */
  target: `0x${string}`;
  /** ABI-encoded calldata for the target. Built by the caller. */
  callData: `0x${string}`;
  /** Native value attached to the target call. Usually `0n`. */
  value: bigint;
  /** Circle Paymaster contract for this chain. Caller-provided. */
  paymasterAddress: `0x${string}`;
  /** USDC asset address for this chain — approved to the paymaster. */
  usdcTokenAddress: `0x${string}`;
  /**
   * Max USDC amount (6-decimal units) the paymaster may pull for gas.
   * Bounds the approve in the UserOp preamble — keep it snug.
   */
  paymasterApproveAmount: bigint;
  /** Bundler RPC endpoint (ERC-4337). Served by task 37's proxy. */
  bundlerUrl: string;
}

/**
 * Return shape of `sendUserOpWithUsdcPaymaster`. Only the bundler's
 * `userOpHash` is surfaced — callers poll the bundler (or the task 38
 * receipt endpoint) to land a tx hash.
 */
export interface SendUserOpResult {
  userOpHash: `0x${string}`;
}

export interface UpgradeToSmartAccountArgs {
  wallet: TWallet;
  chain: ChainConfig;
}

export interface UpgradeToSmartAccountResult {
  transactionHash: string;
  smartAccountAddress: string;
}

/**
 * Arguments for `WalletKitAdapter.sendNativeTransfer`.
 *
 * `amount` is the raw native unit (wei for EVM, lamports for Solana, …) so
 * callers never have to juggle human-denominated strings at the adapter
 * boundary.
 */
export interface NativeTransferArgs {
  wallet: TWallet;
  to: string;
  amount: bigint;
  chain: ChainConfig;
}

/**
 * Arguments for `WalletKitAdapter.sendTokenTransfer`.
 *
 * `amount` is the raw token unit (smallest denomination — e.g. 6-decimal
 * USDC units, 9-decimal SPL token units) so callers never convert at the
 * adapter boundary. `contractAddress` is the ERC-20 contract (EVM) or SPL
 * mint address (Solana).
 */
export interface TokenTransferArgs {
  wallet: TWallet;
  to: string;
  amount: bigint;
  chain: ChainConfig;
  contractAddress: string;
  decimals: number;
}

/**
 * Optional `name` tag applied to newly-created wallets. Kept loose so both
 * EVM and Solana implementations can match the `TWalletCreationParams`
 * shape without forcing a rigid call signature on future chains.
 */
export interface CreateWalletFromPrivateKeyParams {
  privateKey: string;
  name?: string;
}

export interface CreateWalletFromMnemonicParams {
  mnemonic: string;
  name?: string;
}

export interface EstimateMaxTransferableArgs {
  balance: bigint;
  chain: ChainConfig;
  from: string;
  to?: string;
}

export interface TruncateAddressOptions {
  start?: number;
  end?: number;
}

/**
 * Arguments for `WalletKitAdapter.sendContractTransaction` — sends an
 * arbitrary contract call (pre-encoded calldata) via the wallet's signer.
 * Used by the onchain settlement rail to call `processMerchantPayment`
 * on the TakumiWallet contract.
 */
export interface SendContractTransactionArgs {
  wallet: TWallet;
  chain: ChainConfig;
  to: `0x${string}`;
  data: `0x${string}`;
  value?: bigint;
}

/**
 * Arguments for `WalletKitAdapter.signAndExecuteSuiPtb` — signs and
 * executes a pre-built Programmable Transaction Block (base64 BCS, the
 * `sui-ptb` `UnsignedCall` payload). Sui-only; other kits leave the method
 * `undefined`. Consumers presence-check per chain-extension discipline.
 */
export interface SignAndExecuteSuiPtbArgs {
  /** Paying wallet bound to the session (SI-1, intent.wallet discipline). */
  wallet: TWallet;
  chain: ChainConfig;
  /** === `UnsignedCall.transactionBlockBase64` for kind "sui-ptb". */
  ptbBase64: string;
}

/**
 * Arguments for `WalletKitAdapter.sendAnchorInstruction` — broadcasts a
 * Solana transaction containing Anchor program instructions. Used by the
 * onchain settlement rail to call TakumiPay program instructions
 * (`processMerchantPaymentSol/Token`, `createTransactionSol/Token`,
 * `depositPoints`). Solana-only; EVM kit leaves this `undefined`.
 * Consumers presence-check per chain-extension discipline.
 */
export interface SendAnchorInstructionArgs {
  wallet: TWallet;
  chain: ChainConfig;
  instructions: TransactionInstruction[];
  additionalSigners?: Signer[];
  addressLookupTables?: AddressLookupTableAccount[];
  durableNonce?: { nonceAccount: PublicKey; nonceAuthority: Signer };
  feePayer?: { publicKey: PublicKey; mode: "user" | "sponsored" };
}

/**
 * Serialized, plain-object ERC-7710 delegation configurations (spec
 * Phase 2 §5.1). Deliberately SDK-free so UI screens and the local
 * `PermissionGrantStore` can model delegations without importing
 * `@metamask/smart-accounts-kit` classes. `EvmWalletKit` translates
 * these into the SDK's `ScopeType` / `CaveatType` shapes at the port
 * boundary; Solana / Sui never see them.
 */
export interface DelegationScope {
  type:
    | "erc20TransferAmount"
    | "nativeTokenTransferAmount"
    | "functionCall"
    | "erc20PeriodTransfer"
    | "nativeTokenPeriodTransfer";
  /** ERC-20 token / asset address for the transfer-amount scopes. */
  tokenAddress?: string;
  /** Hard cap in raw token units (6-decimal micros for USDC). */
  maxAmount?: bigint;
  /** Recurring-allowance amount per `periodDuration`. */
  periodAmount?: bigint;
  /** Period length in seconds (e.g. 604_800 for weekly). */
  periodDuration?: number;
  /** Target contract addresses for `functionCall`. */
  targets?: string[];
  /** Allowed function selectors / signatures for `functionCall`. */
  methods?: string[];
}

/**
 * A single onchain caveat (boundary enforced during redemption). Maps
 * 1:1 onto the SDK `CaveatType` enum inside `EvmWalletKit`.
 */
export interface CaveatConfig {
  type: "timestamp" | "limitedCalls" | "allowedTargets" | "allowedMethods";
  /** Expiry — Unix epoch in **seconds** — for the `timestamp` caveat. */
  expiresAt?: number;
  /** Max number of execution calls for the `limitedCalls` caveat. */
  limit?: number;
  /** Allowlist of target addresses for the `allowedTargets` caveat. */
  targets?: string[];
  /** Allowlist of selectors / signatures for the `allowedMethods` caveat. */
  methods?: string[];
}

/**
 * Encoded caveat struct as produced by the SDK — `enforcer`/`terms`/`args`
 * hex tuples. Plain-object so it round-trips through `JSON.stringify`
 * when persisted alongside a `PermissionGrant`.
 */
export interface CaveatStruct {
  enforcer: `0x${string}`;
  terms: `0x${string}`;
  args: `0x${string}`;
}

/**
 * A (optionally signed) ERC-7710 delegation. `signature` is the only
 * field that is absent on the unsigned struct returned by
 * `createDelegation`; `signDelegation` fills it in.
 */
export interface DelegationStruct {
  delegate: `0x${string}`;
  delegator: `0x${string}`;
  authority: `0x${string}`;
  caveats: CaveatStruct[];
  salt: `0x${string}`;
  signature: `0x${string}`;
}

export interface CreateDelegationArgs {
  wallet: TWallet;
  chain: ChainConfig;
  /** Delegate (redeemer) address — e.g. the AI agent / relayer. */
  delegate: string;
  scope: DelegationScope;
  caveats?: CaveatConfig[];
  /** 32-byte hex replay-protection salt. Defaults to zero in the kit. */
  salt?: string;
  /** Parent-delegation authority. Defaults to the root authority. */
  authority?: string;
}

export interface SignDelegationArgs {
  wallet: TWallet;
  chain: ChainConfig;
  delegation: Omit<DelegationStruct, "signature">;
}

export interface EncodeDelegationsArgs {
  chain: ChainConfig;
  delegations: DelegationStruct[];
}

// ── 1Shot Relayer gas abstraction (spec Phase 3 §5.1) ──────────────────
//
// Namespace-agnostic shapes for the 1Shot public relayer. Deliberately
// SDK-free and viem-free (this module runs under the Node test harness):
// the EVM kit translates these into JSON-RPC payloads at the port
// boundary in `services/walletKit/evm/relayer.ts`. Solana / Sui never see
// them — the matching methods stay `undefined` on those kits.

/** An ERC-20 token the relayer accepts as gas payment on a given chain. */
export interface RelayerToken {
  address: string;
  symbol: string;
  decimals: number;
}

/** Per-chain relayer capabilities resolved via `relayer_getCapabilities`. */
export interface RelayerChainCapabilities {
  /**
   * The address the delegation must be granted **to** (the relayer's
   * redemption account). SI-4: the delegation `delegate` MUST equal this.
   */
  targetAddress: string;
  /** The address gas fees must be transferred to. */
  feeCollector: string;
  tokens: RelayerToken[];
}

/** Map of viem `chainId` → capabilities. */
export interface RelayerCapabilities {
  [chainId: number]: RelayerChainCapabilities;
}

export interface GetRelayerFeeDataArgs {
  chain: ChainConfig;
  /** Contract address of the stablecoin used to pay gas. */
  token: string;
}

export interface RelayerFeeData {
  /** Native gas price in wei. */
  gasPrice: bigint;
  /**
   * Native-token price expressed in the payment token's whole units
   * (e.g. `2000` ≈ 2000 USDC per 1 ETH). Combine with `gasPrice`,
   * `tokenDecimals`, and `1e18` to derive a payment-token-atoms fee — see
   * `computeRoughFee`. NOT a direct wei→atoms multiplier.
   */
  rate: number;
  /** Floor fee in payment-token **atoms** (≈ 0.01 in the token). */
  minFee: bigint;
  /** Payment token decimals — needed to scale `rate` into atoms. */
  tokenDecimals: number;
  /** Quote validity — UNIX seconds; treat anything past as stale. */
  expiry: number;
  /** Signed price-lock quote. */
  context: string;
}

/**
 * A single execution leg the relayer redeems on the user's behalf.
 *
 * Wire field is `target` (not `to`) per the live 1Shot API
 * (`schemas.md#Execution7710`). `value` is native wei; the kit serializes
 * it to a `0x`-hex quantity at the JSON-RPC boundary.
 */
export interface RelayerExecution {
  target: string;
  value: bigint;
  data: string;
}

/**
 * One bundle entry: a signed delegation chain plus the executions the
 * relayer runs under it. `permissionContext` is length-1 for a direct
 * delegation; sponsor + delegator flows pass two bundle entries. Each
 * entry's `permissionContext` carries the *structured* signed
 * `DelegationStruct[]` — NOT the single `encodeDelegations` hex (that
 * encoding is for a different, on-chain redeemer, not this relayer API).
 */
export interface RelayerBundleEntry {
  permissionContext: DelegationStruct[];
  executions: RelayerExecution[];
}

/**
 * One EIP-7702 authorization-list entry (`schemas.md#AuthorizationListEntry`).
 * At most one is allowed per relayer request. Produced by
 * `WalletKitAdapter.signEip7702Authorization`.
 */
export interface RelayerAuthorizationEntry {
  address: string;
  chainId: number;
  nonce: number;
  r: string;
  s: string;
  yParity: number;
}

export interface Estimate7710TransactionArgs {
  chain: ChainConfig;
  transactions: RelayerBundleEntry[];
  /** ≤1 entry; for an in-flight EIP-7702 upgrade combined with the send. */
  authorizationList?: RelayerAuthorizationEntry[];
}

export interface Estimate7710TransactionResult {
  success: boolean;
  /** Fee to pay in the payment token's atoms, floored at `minFee`. */
  requiredPaymentAmount?: bigint;
  /** First parsed payment token (the mock-fee execution's token). */
  paymentTokenAddress?: string;
  /** Map of chainId (string) → summed gas units (decimal strings). */
  gasUsed?: Record<string, string>;
  /** Signed price-lock context to pass as `send7710Transaction.context`. */
  context?: string;
  /** Populated when `success === false`. Friendly to the caller, never raw. */
  error?: string;
}

export interface Send7710TransactionArgs {
  chain: ChainConfig;
  transactions: RelayerBundleEntry[];
  /** Signed price-lock `context` returned from `estimate7710Transaction`. */
  context: string;
  /** ≤1 entry; for an in-flight EIP-7702 upgrade combined with the send. */
  authorizationList?: RelayerAuthorizationEntry[];
  /** Optional webhook destination for signed status events (≤256 chars). */
  destinationUrl?: string;
  /** Optional opaque client correlation label (≤256 chars). */
  memo?: string;
}

export interface Send7710TransactionResult {
  /** 0x + 64 hex chars. */
  taskId: string;
}

export interface GetRelayerStatusArgs {
  chain: ChainConfig;
  taskId: string;
}

/**
 * Normalised task status. `status` is the friendly label; `statusCode`
 * is the raw relayer code (`100` Pending, `110` Submitted, `200`
 * Confirmed, `400` Rejected, `500` Reverted) so callers can distinguish
 * terminal failure modes without re-deriving them.
 */
export interface RelayerStatus {
  status: "pending" | "submitted" | "success" | "failed";
  statusCode: number;
  /** Present once the task lands on-chain (Submitted / Confirmed). */
  transactionHash?: string;
  /** Echoed back when `memo` was set on submit. */
  memo?: string;
}

export interface SignEip7702AuthorizationArgs {
  wallet: TWallet;
  chain: ChainConfig;
}

// ── Agent-initiated x402 micropayments (spec Phase 5 §5.1) ─────────────
//
// Plain, serializable shapes (no `@metamask/x402` / `@x402/*` SDK classes
// leak across the port). The EVM kit translates them into the relayer /
// facilitator settlement at the port boundary in
// `services/walletKit/evm/x402Settle.ts`; Solana / Sui leave
// `settleX402Payment` `undefined` and never see them.

/**
 * Normalised x402 "exact" challenge for the ERC-7710 settlement path.
 * Superset-compatible with the EIP-3009 `X402Challenge` in nanopay so the
 * shared parsing conventions can emit either; `assetTransferMethod`
 * discriminates the delegation rail (spec §5.1).
 */
export interface X402Erc7710Challenge {
  scheme: "exact";
  /** CAIP-2, e.g. `"eip155:84532"`. */
  network: string;
  /** USDC atoms, decimal string (bigint-safe over JSON). */
  maxAmountRequired: string;
  payTo: `0x${string}`;
  /** USDC asset address on `network`. */
  asset: `0x${string}`;
  resource: string;
  /** Facilitator URL named by the seller (Rail A). */
  facilitator?: string | null;
  /** Gates the delegation rail. */
  assetTransferMethod: "erc7710";
  maxTimeoutSeconds?: number;
}

export interface SettleX402PaymentArgs {
  /** Paying wallet bound to the agent session (SI-4). */
  wallet: TWallet;
  chain: ChainConfig;
  challenge: X402Erc7710Challenge;
  /** Persisted, already-signed user→agent allowance (the budget). */
  delegation: DelegationStruct;
  /** Remaining spendable atoms for this allowance (budget gate, §6.2). */
  remainingBudgetAtoms: bigint;
}

/**
 * Result of an x402 settlement attempt. `reason` (on `failed`) is always
 * hand-written friendly copy — never a raw relayer / facilitator body
 * (CLAUDE.md user-facing-errors rule, SI-6).
 */
export type SettleX402PaymentResult =
  | {
      status: "settled";
      proof: string;
      rail: "facilitator" | "relayer";
      txHash?: string;
      spentAtoms: bigint;
    }
  | {
      status: "over_budget";
      requestedAtoms: bigint;
      remainingBudgetAtoms: bigint;
    }
  | { status: "failed"; reason: string };

export interface WalletKitAdapter {
  readonly namespace: Namespace;

  // ── Wallet creation & validation ────────────────────────────────────
  validateAddress(address: string): boolean;
  validatePrivateKey(privateKey: string): boolean;
  validateMnemonic(mnemonic: string): boolean;

  createWalletFromPrivateKey(
    params: CreateWalletFromPrivateKeyParams,
  ): Promise<TWallet>;
  createWalletFromMnemonic(
    params: CreateWalletFromMnemonicParams,
  ): Promise<TWallet>;

  generateMnemonic(): string;

  // ── Keys & signers (delegates to walletService dwell sites) ─────────
  /**
   * Returns the kit-specific signer handle for `wallet` (viem `Account`,
   * `KeyPairSigner`, …). The return type is deliberately `unknown | null`
   * so EVM and Solana can return different shapes without leaking types
   * across the port. Callers narrow via `walletKitRegistry.get(ns)`.
   */
  getSignerForWallet(wallet: TWallet): Promise<unknown | null>;

  // ── Reads ───────────────────────────────────────────────────────────
  getNativeBalance(address: string, chain: ChainConfig): Promise<bigint>;

  /**
   * Returns the raw token balance for a non-native token identified by
   * `contractAddress`. EVM: ERC-20 `balanceOf`; Solana: SPL Token /
   * Token-2022 ATA lookup. Returns `0n` when the account has no balance.
   * Future chains (SUI, etc.) implement this for their own token standard.
   */
  getTokenBalance(
    address: string,
    chain: ChainConfig,
    contractAddress: string,
  ): Promise<bigint>;

  // ── Writes ──────────────────────────────────────────────────────────
  /** Returns tx hash (EVM) or signature (Solana) as a string. */
  sendNativeTransfer(args: NativeTransferArgs): Promise<string>;

  /**
   * Transfers a non-native token (ERC-20 on EVM, SPL on Solana).
   * Returns tx hash (EVM) or signature (Solana) as a string.
   */
  sendTokenTransfer(args: TokenTransferArgs): Promise<string>;

  /**
   * Computes the max transferable amount given `balance`, accounting for
   * fee / rent reserves. Implementations may consult the network via
   * `chain` (gas estimate, rent exemption, …).
   */
  estimateMaxTransferable(args: EstimateMaxTransferableArgs): Promise<bigint>;

  // ── Auth ────────────────────────────────────────────────────────────
  /**
   * Signs a backend-issued nonce message for authentication (SIWE on
   * EVM, SIWS on Solana). Returns the signature as a string whose
   * encoding is namespace-appropriate (hex for EVM, base58 for Solana).
   * Consumers call this without branching on namespace — each kit owns
   * its signing primitive and output encoding.
   */
  signAuthMessage(wallet: TWallet, message: string): Promise<string>;

  // ── Display ─────────────────────────────────────────────────────────
  /** e.g. `"0.0123 ETH"` / `"0.0123 SOL"`. */
  formatNativeAmount(raw: bigint, chain: ChainConfig): string;
  /** Inverse of `formatNativeAmount` — parses a human string to raw units. */
  parseNativeAmount(human: string, chain: ChainConfig): bigint;
  truncateAddress(address: string, opts?: TruncateAddressOptions): string;

  // ── Gasless USDC payment signers (per-namespace capability) ─────────
  /**
   * Signs EIP-3009 `TransferWithAuthorization` typed-data bound to
   * Circle's `GatewayWallet` contract (spec §5.5). Returns the raw
   * 65-byte signature (`0x`-prefixed hex). EVM-only; Solana kit leaves
   * this `undefined`. Consumers dispatch via presence-of-method rather
   * than `if (namespace === "eip155")` branches.
   */
  signTransferWithAuthorization?(
    args: SignTransferWithAuthorizationArgs,
  ): Promise<`0x${string}`>;

  /**
   * Submits an ERC-4337 UserOperation whose gas is sponsored by
   * Circle Paymaster in USDC (spec §5.4, §12 Q6). The UserOp bundles a
   * USDC `approve(paymaster, amount)` preamble with the caller's
   * target call (e.g. `GatewayWallet.deposit`). For a plain EOA the
   * adapter attaches an EIP-7702 authorization so Entry-Point v0.8
   * treats the EOA as a `Simple7702Account`. EVM-only; Solana kit
   * leaves this `undefined`. Consumers presence-check.
   */
  sendUserOpWithUsdcPaymaster?(
    args: SendUserOpWithUsdcPaymasterArgs,
  ): Promise<SendUserOpResult>;

  /**
   * Optional EIP-7702 upgrade capability. Upgrades an EOA to a smart contract account.
   * EVM-only; Solana/Sui kits leave this undefined.
   */
  upgradeToSmartAccount?(
    args: UpgradeToSmartAccountArgs,
  ): Promise<UpgradeToSmartAccountResult>;

  /**
   * Optional check to verify if a wallet is already upgraded/active as a smart account.
   */
  isSmartAccountActive?(wallet: TWallet, chain: ChainConfig): Promise<boolean>;

  // ── ERC-7710 onchain delegation (spec Phase 2 §5.2) ─────────────────
  /**
   * Builds an unsigned ERC-7710 delegation from a serialized scope +
   * caveats, mapping them onto the SDK's `ScopeType` / `CaveatType`.
   * EVM-only; Solana / Sui leave this `undefined`. Consumers presence-
   * check rather than branching on namespace.
   */
  createDelegation?(
    args: CreateDelegationArgs,
  ): Promise<Omit<DelegationStruct, "signature">>;

  /**
   * Signs an unsigned ERC-7710 delegation with the wallet's smart-account
   * keys (EIP-712 over the delegation struct). Returns the raw signature.
   * Biometric gating is the caller's responsibility (SI-1). EVM-only.
   */
  signDelegation?(args: SignDelegationArgs): Promise<`0x${string}`>;

  /**
   * Encodes one or more signed delegations into the single hex
   * `delegationContext` that a Phase 3 relayer / redeemer consumes.
   * EVM-only; Solana / Sui leave this `undefined`.
   */
  encodeDelegations?(args: EncodeDelegationsArgs): Promise<string>;

  // ── 1Shot Relayer gas abstraction (spec Phase 3 §5.2) ───────────────
  //
  // Gasless execution rail. The relayer redeems a signed ERC-7710
  // delegation on-chain and charges gas in a stablecoin (USDC) instead
  // of native ETH. EVM-only; Solana / Sui leave every method `undefined`
  // so shared UI / agent loops dispatch via presence-of-method rather
  // than branching on namespace (G6 / G7, chain-extension discipline).

  /**
   * Discovers supported chains, accepted payment tokens, the relayer's
   * redemption `targetAddress` (the delegation `delegate`, SI-4) and the
   * `feeCollector` for the active chain. Cache per session.
   */
  getRelayerCapabilities?(args: {
    chain: ChainConfig;
  }): Promise<RelayerCapabilities>;

  /**
   * Rough gas-fee quote + price-lock context **before** the bundle is
   * built — for pre-sign UI fee display. Prefer `estimate7710Transaction`
   * once the signed bundle exists.
   */
  getRelayerFeeData?(args: GetRelayerFeeDataArgs): Promise<RelayerFeeData>;

  /**
   * Validates the delegation, runs a gas simulation, and locks a price
   * quote for a signed bundle. Returns `{ success: false, error }` on
   * validation / simulation failure rather than throwing (G5 loop).
   */
  estimate7710Transaction?(
    args: Estimate7710TransactionArgs,
  ): Promise<Estimate7710TransactionResult>;

  /**
   * Submits the delegation-authorized execution bundle to the relayer
   * with the price-lock `feeContext` from estimate. Returns a `taskId`
   * for async status tracking.
   */
  send7710Transaction?(
    args: Send7710TransactionArgs,
  ): Promise<Send7710TransactionResult>;

  /** Queries the execution status of a submitted relayer task. */
  getRelayerTransactionStatus?(
    args: GetRelayerStatusArgs,
  ): Promise<RelayerStatus>;

  /**
   * Signs a single EIP-7702 `authorizationList` entry so an un-upgraded
   * EOA can be upgraded to the stateless-7702 delegator *in the same*
   * relayer request as its first sponsored send. Reuses the allowlist /
   * bytecode guards from the standalone upgrade path. EVM-only.
   */
  signEip7702Authorization?(
    args: SignEip7702AuthorizationArgs,
  ): Promise<RelayerAuthorizationEntry>;

  /**
   * Settle a single x402 "exact" challenge using a pre-signed ERC-7710
   * allowance delegation (spec Phase 5 §5.2). Selects the facilitator or
   * 1Shot-relayer rail from the challenge, enforces the budget + fee
   * safety bounds, and returns an `X-PAYMENT` proof. Composes the Phase 2
   * delegation + Phase 3 relayer methods — no new on-chain primitive.
   * EVM-only; Solana / Sui leave this `undefined`. Consumers presence-
   * check rather than branching on namespace.
   */
  settleX402Payment?(
    args: SettleX402PaymentArgs,
  ): Promise<SettleX402PaymentResult>;

  /**
   * Signs an x402 SVM-scheme versioned Solana transaction pre-built by
   * the backend (spec §5.2.1, §5.5, milestone M6). Path B-SVM rail for
   * Solana payers — mirrors `signTransferWithAuthorization` on the EVM
   * side but over a different primitive: the facilitator hands us a
   * partially-signed versioned tx (ComputeBudget × 2, TransferChecked,
   * optional Memo) with itself as `feePayer`, the wallet adds the user
   * signature slot, and the facilitator later attaches the feePayer
   * signature and submits. Solana-only; EVM kit leaves `undefined`.
   * Consumers (path selector, task 41) presence-check rather than
   * branching on namespace — this is the chain-extension discipline
   * (`feedback_chain_extension_discipline.md`) in action.
   *
   * Returns the updated base64-encoded wire transaction with the
   * user's signature attached. Never broadcasts.
   */
  signX402SvmPayment?(args: SignX402SvmPaymentArgs): Promise<string>;

  /**
   * Sends a raw contract transaction with pre-encoded calldata. Used by
   * the onchain settlement rail (`pathOnchainSettlement.ts`) to call
   * `processMerchantPayment` on the TakumiWallet contract. EVM-only;
   * Solana kit leaves this `undefined`. Consumers presence-check.
   */
  sendContractTransaction?(args: SendContractTransactionArgs): Promise<string>;

  /**
   * Broadcasts a Solana transaction containing Anchor program instructions.
   * Used by the onchain settlement rail (`pathOnchainSettlementSvm.ts`) to
   * call TakumiPay program instructions. Solana-only; EVM kit leaves this
   * `undefined`. Consumers presence-check per chain-extension discipline.
   */
  sendAnchorInstruction?(args: SendAnchorInstructionArgs): Promise<string>;

  /**
   * Signs and executes a pre-built PTB (base64 BCS — the `sui-ptb`
   * `UnsignedCall` payload) with the wallet's Sui signer. The general
   * Sui-PTB submitter: it consumes the `transactionBlockBase64` any
   * `UnsignedCall` carries, so the same method serves the Intent Engine and
   * any future Sui `DefiProtocolAdapter`. Sui-only; other kits leave it
   * `undefined`. Consumers presence-check. Returns the base58 digest.
   */
  signAndExecuteSuiPtb?(args: SignAndExecuteSuiPtbArgs): Promise<string>;

  // ── Optional capability flags ───────────────────────────────────────
  /** Whether this kit supports non-native token transfers. */
  supportsTokenTransfer?: boolean;
  /** `true` by default; future MPC / HW-only chains return `false`. */
  supportsPrivateKeyImport?: boolean;
  /** Human-readable chain family label for UI pickers. */
  displayName?: string;
  /** Icon URL for UI pickers. */
  iconUrl?: string;

  // ── Approval-sheet presentation hooks ───────────────────────────────
  /**
   * Hex colour (e.g. `"#627EEA"`) used as the accent for this chain's
   * namespace chip in approval sheets. Omitting falls back to a neutral
   * grey so adding a new chain without a brand colour still renders.
   */
  brandColor?: string;
  /**
   * Returns the chip label shown on the connect sheet (e.g.
   * `"Solana · Mainnet"`). The payload is whatever the adapter emits for
   * its `connect` intent — kits narrow it themselves. If omitted the sheet
   * falls back to `displayName`.
   */
  formatConnectChipLabel?(payload: unknown): string;
  /**
   * When `true`, the connect sheet gates approval behind the platform
   * biometric prompt. Kits opt in per chain (Solana ships with this on;
   * EVM connect is a free grant for parity with MetaMask). Default `false`.
   */
  requireBiometricForConnect?: boolean;

  // ── Chain identification hooks (used by `services/walletKit/chainInfo.ts`) ──
  /**
   * Returns the native chain identifier for `chain`. EVM kits return the
   * viem `chain.id` (number); Solana returns the cluster string. Returns
   * `null` when the chain does not belong to this kit's namespace, so
   * callers that receive a cross-namespace chain get a predictable `null`
   * instead of silently passing `undefined` into a chain-specific client.
   */
  getChainId?(chain: ChainConfig): number | string | null;
  /**
   * Returns a human-readable label for `chain` (e.g. `"Ethereum Mainnet"`,
   * `"Solana Mainnet"`). Falls back to `displayName` via
   * `services/walletKit/chainInfo.ts#formatChainLabel` when omitted.
   */
  formatChainLabel?(chain: ChainConfig): string | null;
  /**
   * Returns the native currency ticker for `chain` — `"ETH"`, `"SOL"`,
   * `"MATIC"`, etc. Called by the agent-mode wallet-context builder
   * (`components/home/TakumiAgent/AgentMode.tsx`) so shared code can stay
   * chain-agnostic per §4.5 space-docking. Returns `null` when `chain`
   * doesn't belong to this kit.
   */
  nativeSymbol?(chain: ChainConfig): string | null;

  /**
   * Builds a block-explorer URL for `txHash` on `chain`. EVM kits read
   * the chain's configured `blockExplorers.default.url` and append
   * `/tx/{hash}`; Solana kits return the cluster-aware `explorer.solana.com`
   * URL. Returns `null` when the chain doesn't belong to this kit or no
   * explorer is configured. UI consumers (transfer success popup, agent
   * receipts) call this without branching on namespace.
   */
  buildTxExplorerUrl?(txHash: string, chain: ChainConfig): string | null;

  /**
   * Returns the backend auth-nonce `chainSlug` for `chain` (e.g.
   * `"solana-devnet"`, `"sui-testnet"`). Solana/Sui implement this; EVM
   * leaves it undefined because EVM nonce requests key on the numeric
   * `chainId` instead. Consumers go through
   * `services/walletKit/chainInfo.ts#getNonceParams`, which falls back to
   * `getEvmChainId` when this returns `null`. Returns `null` when `chain`
   * doesn't belong to this kit.
   */
  getAuthChainSlug?(chain: ChainConfig): string | null;
  /**
   * The family's mainnet auth-nonce `chainSlug` (e.g. `"solana-mainnet"`).
   * Used by `chainInfo.ts#getNonceParams` as the race-safe fallback when
   * the active chain momentarily lags a wallet switch (see auth.tsx). Only
   * kits that expose `getAuthChainSlug` set this; EVM omits both.
   */
  defaultAuthChainSlug?: string;
  /**
   * True when the `/blockchains` row `row` is the same network as `chain`.
   * EVM matches on `row.isEVM && row.chainId === chainId`; Solana/Sui match
   * on the `chainSlug` prefix (with a name/rpc fallback for rows that
   * predate `chainSlug`) plus testnet parity. Lets balance/payment screens
   * resolve the matching API row without branching on namespace. Returns
   * `false` when `chain` doesn't belong to this kit.
   */
  matchesBlockchainRow?(chain: ChainConfig, row: TBlockchain): boolean;
  /**
   * Backend payment-rail selector for `chain` (`"evm"` / `"solana"`), used
   * by pay-merchant intent creation. Kits without a dedicated rail omit it;
   * `chainInfo.ts#preferredChainRail` defaults those to `"evm"` to preserve
   * the historical "solana or evm" mapping.
   */
  preferredPaymentRail?: "evm" | "solana";
}
