/**
 * `WalletKitAdapter` — first-party wallet docking port.
 *
 * Mirrors the `ChainAdapter` pattern (see `services/chains/types.ts`), but
 * covers first-party mobile wallet operations that are NOT dApp-originated:
 * keypair creation / import, address validation, native balance fetch,
 * native send, MAX-amount calculation, human/raw amount formatting.
 *
 * Every namespace (`eip155`, `solana`, …) implements this interface and
 * registers itself via `walletKitRegistry` so that UI code (`app/send.tsx`,
 * `app/wallet.tsx`, add-wallet sheets, …) can stay namespace-agnostic.
 *
 * Rules (enforced by spec §4.5 + Task 04):
 *   - No `react` / `react-native` imports — this module must run under a
 *     Node test harness.
 *   - No `viem` imports — viem lives inside `services/walletKit/evm/` only.
 */

import type { ChainConfig } from "@/constants/configs/chainConfig";
import type { TWallet } from "@/constants/types/walletTypes";
import type { Namespace } from "@/services/chains/types";

export type { Namespace };

/**
 * Arguments for `WalletKitAdapter.signTransferWithAuthorization` — the
 * EIP-3009 `TransferWithAuthorization` primitive Circle Nanopayments
 * accepts. EVM-only; Solana kit leaves the method `undefined`.
 *
 * Crucial detail (spec §5.5): the EIP-712 domain points at Circle's
 * `GatewayWallet` contract on the source chain — NOT the USDC contract.
 * `{ gatewayWallet, domainName, domainVersion }` arrive pre-fetched via
 * `GET /gateway/v1/x402/supported` at backend boot and are piped through
 * `PaymentIntent.nanopay.domain`. Signing against the USDC contract's
 * domain will pass `/gateway/v1/x402/verify` but fail settle — don't.
 *
 * The adapter does NOT broadcast. Submission is the caller's job.
 */
export interface SignTransferWithAuthorizationArgs {
  wallet: TWallet;
  chain: ChainConfig;
  /** EIP-712 `verifyingContract` — the Gateway batched-wallet contract. */
  gatewayWallet: `0x${string}`;
  /** e.g. `"GatewayWalletBatched"` — from `/gateway/v1/x402/supported`. */
  domainName: string;
  /** e.g. `"1"` — from `/gateway/v1/x402/supported`. */
  domainVersion: string;
  /** USDC asset address — embedded in the `TransferWithAuthorization` struct. */
  usdc: `0x${string}`;
  from: `0x${string}`;
  to: `0x${string}`;
  /** 6-decimal USDC units. */
  valueMicros: bigint;
  /** Unix seconds; usually 0. */
  validAfter: number;
  /**
   * Unix seconds. MUST be `≥ now + 3 days` or Gateway rejects with
   * `authorization_validity_too_short`. Adapter enforces this guard
   * pre-sign so the UX can surface a typed error before the keystore
   * is touched.
   */
  validBefore: number;
  /** 32-byte random, generated by the server. */
  nonce: `0x${string}`;
}

/**
 * Minimum signer validity window Circle Gateway enforces — 3 days in
 * unix seconds. Exported so tests and callers can reference the same
 * constant instead of re-deriving it.
 */
export const GATEWAY_VALID_BEFORE_MIN_SECONDS = 259_200;

/**
 * Typed error thrown by `signTransferWithAuthorization` when the
 * incoming `validBefore` is below `now + 3 days`. Screens should catch
 * by `name === "AuthorizationValidityTooShortError"` and map to a UX
 * string without re-parsing the message.
 */
export class AuthorizationValidityTooShortError extends Error {
  readonly name = "AuthorizationValidityTooShortError";
  readonly validBefore: number;
  readonly minimumValidBefore: number;
  constructor(args: { validBefore: number; minimumValidBefore: number }) {
    super(
      `validBefore (${args.validBefore}) is below the Gateway minimum (${args.minimumValidBefore}); ` +
        `Circle requires validBefore ≥ now + 3 days.`,
    );
    this.validBefore = args.validBefore;
    this.minimumValidBefore = args.minimumValidBefore;
  }
}

/**
 * Arguments for `WalletKitAdapter.signX402SvmPayment` — the Solana
 * counterpart to `signTransferWithAuthorization` for the Path B-SVM rail
 * (spec §5.2.1, §5.5, milestone M6). Solana-only; EVM kits leave this
 * `undefined`. Consumers presence-check rather than branching on
 * `namespace === "solana"`.
 *
 * Unlike EIP-3009 (where the signer produces a 65-byte typed-data
 * signature the backend stuffs into an on-chain call), the SVM x402
 * scheme hands the wallet a *pre-built* base64-encoded versioned
 * transaction. The facilitator is the `feePayer` — it has already
 * authored the ComputeBudget / TransferChecked / (optional) Memo
 * instructions per §5.2.1 wire format. The wallet adds its own
 * signature over the message bytes and returns the updated base64 tx;
 * the facilitator later attaches the `feePayer` signature and submits
 * to the network (task 43).
 *
 * Rules the adapter enforces:
 *   - Instruction list is immutable. The facilitator's settle path
 *     rejects any tx whose message bytes differ from what it issued.
 *   - The adapter adds the *user's* signature only — the fee-payer slot
 *     is left untouched (still the caller-supplied placeholder / null).
 *   - No broadcast. Submission is the backend's job (memory:
 *     `feedback_role_separation.md`).
 */
export interface SignX402SvmPaymentArgs {
  wallet: TWallet;
  /** Cluster discriminator carried through to the facilitator POST. */
  cluster: "mainnet-beta" | "devnet";
  /**
   * Base64-encoded versioned Solana transaction, partially signed with
   * a `feePayer` placeholder per §5.2.1. The wallet adds the user's
   * signature and returns the updated base64 blob.
   */
  transaction: string;
}

/**
 * Typed error thrown by `signX402SvmPayment` when the wallet's declared
 * namespace does not match `"solana"`. Separate from the kit-level
 * assert so UI can catch it by `name === "SvmWalletNamespaceMismatchError"`
 * and surface a dedicated string instead of a generic "wrong chain".
 */
export class SvmWalletNamespaceMismatchError extends Error {
  readonly name = "SvmWalletNamespaceMismatchError";
  readonly walletNamespace: string;
  constructor(walletNamespace: string) {
    super(
      `signX402SvmPayment: expected solana wallet, got namespace=${walletNamespace}`,
    );
    this.walletNamespace = walletNamespace;
  }
}

/**
 * Typed error thrown by `signX402SvmPayment` when the wallet has no
 * Solana signer (no keypair materialisable from `expo-secure-store`).
 * Separate error so UX can hint "re-import / re-create wallet" instead
 * of swallowing the generic failure.
 */
export class SvmSignerUnavailableError extends Error {
  readonly name = "SvmSignerUnavailableError";
  readonly walletAddress: string;
  constructor(walletAddress: string) {
    super(`signX402SvmPayment: no Solana signer for wallet ${walletAddress}`);
    this.walletAddress = walletAddress;
  }
}

/**
 * Arguments for `WalletKitAdapter.sendUserOpWithUsdcPaymaster` — the
 * ERC-4337 UserOperation primitive that lets Circle Paymaster pay gas
 * in USDC on Base / Arbitrum (spec §5.4 gasless table, §5.5 adapter
 * surface, §12 Q6 ERC-4337 / EIP-7702 path).
 *
 * The adapter builds a UserOp with a two-call batch: an `approve` on
 * USDC so the paymaster can pull gas funds, and the actual target call
 * (e.g. `GatewayWallet.deposit`). If the wallet is a plain EOA, the
 * adapter attaches an EIP-7702 `authorization` so Entry-Point v0.8
 * treats the EOA as a `Simple7702Account`.
 *
 * `chainId` / Circle Paymaster chain-gating is the **caller's** job —
 * the adapter does not validate the chain against Circle's allowlist
 * (Base / Arbitrum in v1; may expand). Passing an unsupported chainId
 * will result in a bundler 4xx at submit time.
 *
 * EVM-only; Solana kit leaves the method `undefined`. Consumers
 * dispatch via presence-of-method rather than `if (namespace === ...)`.
 */
export interface SendUserOpWithUsdcPaymasterArgs {
  wallet: TWallet;
  chain: ChainConfig;
  /** Target contract being called (e.g. `GatewayWallet` for a deposit). */
  target: `0x${string}`;
  /** ABI-encoded calldata for the target. Built by the caller. */
  callData: `0x${string}`;
  /** Native value attached to the target call. Usually `0n`. */
  value: bigint;
  /** Circle Paymaster contract for this chain. Caller-provided. */
  paymasterAddress: `0x${string}`;
  /** USDC asset address for this chain — approved to the paymaster. */
  usdcTokenAddress: `0x${string}`;
  /**
   * Max USDC amount (6-decimal units) the paymaster may pull for gas.
   * Bounds the approve in the UserOp preamble — keep it snug.
   */
  paymasterApproveAmount: bigint;
  /** Bundler RPC endpoint (ERC-4337). Served by task 37's proxy. */
  bundlerUrl: string;
}

/**
 * Return shape of `sendUserOpWithUsdcPaymaster`. Only the bundler's
 * `userOpHash` is surfaced — callers poll the bundler (or the task 38
 * receipt endpoint) to land a tx hash.
 */
export interface SendUserOpResult {
  userOpHash: `0x${string}`;
}

/**
 * Arguments for `WalletKitAdapter.sendNativeTransfer`.
 *
 * `amount` is the raw native unit (wei for EVM, lamports for Solana, …) so
 * callers never have to juggle human-denominated strings at the adapter
 * boundary.
 */
export interface NativeTransferArgs {
  wallet: TWallet;
  to: string;
  amount: bigint;
  chain: ChainConfig;
}

/**
 * Optional `name` tag applied to newly-created wallets. Kept loose so both
 * EVM and Solana implementations can match the `TWalletCreationParams`
 * shape without forcing a rigid call signature on future chains.
 */
export interface CreateWalletFromPrivateKeyParams {
  privateKey: string;
  name?: string;
}

export interface CreateWalletFromMnemonicParams {
  mnemonic: string;
  name?: string;
}

export interface EstimateMaxTransferableArgs {
  balance: bigint;
  chain: ChainConfig;
  from: string;
  to?: string;
}

export interface TruncateAddressOptions {
  start?: number;
  end?: number;
}

export interface WalletKitAdapter {
  readonly namespace: Namespace;

  // ── Wallet creation & validation ────────────────────────────────────
  validateAddress(address: string): boolean;
  validatePrivateKey(privateKey: string): boolean;
  validateMnemonic(mnemonic: string): boolean;

  createWalletFromPrivateKey(
    params: CreateWalletFromPrivateKeyParams,
  ): Promise<TWallet>;
  createWalletFromMnemonic(
    params: CreateWalletFromMnemonicParams,
  ): Promise<TWallet>;

  generateMnemonic(): string;

  // ── Keys & signers (delegates to walletService dwell sites) ─────────
  /**
   * Returns the kit-specific signer handle for `wallet` (viem `Account`,
   * `KeyPairSigner`, …). The return type is deliberately `unknown | null`
   * so EVM and Solana can return different shapes without leaking types
   * across the port. Callers narrow via `walletKitRegistry.get(ns)`.
   */
  getSignerForWallet(wallet: TWallet): Promise<unknown | null>;

  // ── Reads ───────────────────────────────────────────────────────────
  getNativeBalance(address: string, chain: ChainConfig): Promise<bigint>;

  // ── Writes ──────────────────────────────────────────────────────────
  /** Returns tx hash (EVM) or signature (Solana) as a string. */
  sendNativeTransfer(args: NativeTransferArgs): Promise<string>;

  /**
   * Computes the max transferable amount given `balance`, accounting for
   * fee / rent reserves. Implementations may consult the network via
   * `chain` (gas estimate, rent exemption, …).
   */
  estimateMaxTransferable(args: EstimateMaxTransferableArgs): Promise<bigint>;

  // ── Display ─────────────────────────────────────────────────────────
  /** e.g. `"0.0123 ETH"` / `"0.0123 SOL"`. */
  formatNativeAmount(raw: bigint, chain: ChainConfig): string;
  /** Inverse of `formatNativeAmount` — parses a human string to raw units. */
  parseNativeAmount(human: string, chain: ChainConfig): bigint;
  truncateAddress(address: string, opts?: TruncateAddressOptions): string;

  // ── Gasless USDC payment signers (per-namespace capability) ─────────
  /**
   * Signs EIP-3009 `TransferWithAuthorization` typed-data bound to
   * Circle's `GatewayWallet` contract (spec §5.5). Returns the raw
   * 65-byte signature (`0x`-prefixed hex). EVM-only; Solana kit leaves
   * this `undefined`. Consumers dispatch via presence-of-method rather
   * than `if (namespace === "eip155")` branches.
   */
  signTransferWithAuthorization?(
    args: SignTransferWithAuthorizationArgs,
  ): Promise<`0x${string}`>;

  /**
   * Submits an ERC-4337 UserOperation whose gas is sponsored by
   * Circle Paymaster in USDC (spec §5.4, §12 Q6). The UserOp bundles a
   * USDC `approve(paymaster, amount)` preamble with the caller's
   * target call (e.g. `GatewayWallet.deposit`). For a plain EOA the
   * adapter attaches an EIP-7702 authorization so Entry-Point v0.8
   * treats the EOA as a `Simple7702Account`. EVM-only; Solana kit
   * leaves this `undefined`. Consumers presence-check.
   */
  sendUserOpWithUsdcPaymaster?(
    args: SendUserOpWithUsdcPaymasterArgs,
  ): Promise<SendUserOpResult>;

  /**
   * Signs an x402 SVM-scheme versioned Solana transaction pre-built by
   * the backend (spec §5.2.1, §5.5, milestone M6). Path B-SVM rail for
   * Solana payers — mirrors `signTransferWithAuthorization` on the EVM
   * side but over a different primitive: the facilitator hands us a
   * partially-signed versioned tx (ComputeBudget × 2, TransferChecked,
   * optional Memo) with itself as `feePayer`, the wallet adds the user
   * signature slot, and the facilitator later attaches the feePayer
   * signature and submits. Solana-only; EVM kit leaves `undefined`.
   * Consumers (path selector, task 41) presence-check rather than
   * branching on namespace — this is the chain-extension discipline
   * (`feedback_chain_extension_discipline.md`) in action.
   *
   * Returns the updated base64-encoded wire transaction with the
   * user's signature attached. Never broadcasts.
   */
  signX402SvmPayment?(args: SignX402SvmPaymentArgs): Promise<string>;

  // ── Optional capability flags ───────────────────────────────────────
  /** `false` for Solana in v2.3.0 (no SPL token support yet). */
  supportsTokenTransfer?: boolean;
  /** `true` by default; future MPC / HW-only chains return `false`. */
  supportsPrivateKeyImport?: boolean;
  /** Human-readable chain family label for UI pickers. */
  displayName?: string;
  /** Icon URL for UI pickers. */
  iconUrl?: string;

  // ── Approval-sheet presentation hooks ───────────────────────────────
  /**
   * Hex colour (e.g. `"#627EEA"`) used as the accent for this chain's
   * namespace chip in approval sheets. Omitting falls back to a neutral
   * grey so adding a new chain without a brand colour still renders.
   */
  brandColor?: string;
  /**
   * Returns the chip label shown on the connect sheet (e.g.
   * `"Solana · Mainnet"`). The payload is whatever the adapter emits for
   * its `connect` intent — kits narrow it themselves. If omitted the sheet
   * falls back to `displayName`.
   */
  formatConnectChipLabel?(payload: unknown): string;
  /**
   * When `true`, the connect sheet gates approval behind the platform
   * biometric prompt. Kits opt in per chain (Solana ships with this on;
   * EVM connect is a free grant for parity with MetaMask). Default `false`.
   */
  requireBiometricForConnect?: boolean;

  // ── Chain identification hooks (used by `services/walletKit/chainInfo.ts`) ──
  /**
   * Returns the native chain identifier for `chain`. EVM kits return the
   * viem `chain.id` (number); Solana returns the cluster string. Returns
   * `null` when the chain does not belong to this kit's namespace, so
   * callers that receive a cross-namespace chain get a predictable `null`
   * instead of silently passing `undefined` into a chain-specific client.
   */
  getChainId?(chain: ChainConfig): number | string | null;
  /**
   * Returns a human-readable label for `chain` (e.g. `"Ethereum Mainnet"`,
   * `"Solana Mainnet"`). Falls back to `displayName` via
   * `services/walletKit/chainInfo.ts#formatChainLabel` when omitted.
   */
  formatChainLabel?(chain: ChainConfig): string | null;
  /**
   * Returns the native currency ticker for `chain` — `"ETH"`, `"SOL"`,
   * `"MATIC"`, etc. Called by the agent-mode wallet-context builder
   * (`components/home/TakumiAgent/AgentMode.tsx`) so shared code can stay
   * chain-agnostic per §4.5 space-docking. Returns `null` when `chain`
   * doesn't belong to this kit.
   */
  nativeSymbol?(chain: ChainConfig): string | null;
}
