import { TCryptoAsset } from "../types/assetTypes";

export const SAMPLE_ASSETS: TCryptoAsset[] = [
  {
    id: "1",
    symbol: "BTC",
    name: "Bitcoin",
    logo: "₿",
    balance: "0.0025",
    value: "1,250.00",
    change: "+2.5%",
  },
  {
    id: "2",
    symbol: "ETH",
    name: "Ethereum",
    logo: "Ξ",
    balance: "0.42",
    value: "840.00",
    change: "-1.2%",
  },
  {
    id: "3",
    symbol: "BNB",
    name: "Binance Coin",
    logo: "B",
    balance: "2.75",
    value: "825.00",
    change: "+3.2%",
  },
  {
    id: "4",
    symbol: "MATIC",
    name: "Polygon",
    logo: "M",
    balance: "150.0",
    value: "225.00",
    change: "+4.7%",
  },
  {
    id: "5",
    symbol: "USDT",
    name: "Tether",
    logo: "₮",
    balance: "325.75",
    value: "325.75",
    change: "+0.1%",
  },
  {
    id: "6",
    symbol: "USDC",
    name: "USD Coin",
    logo: "$",
    balance: "250.00",
    value: "250.00",
    change: "+0.0%",
  },
  {
    id: "7",
    symbol: "DAI",
    name: "Dai",
    logo: "◈",
    balance: "175.50",
    value: "175.50",
    change: "-0.1%",
  },
  {
    id: "8",
    symbol: "SOL",
    name: "Solana",
    logo: "S",
    balance: "12.5",
    value: "625.00",
    change: "+5.7%",
  },
  {
    id: "9",
    symbol: "AVAX",
    name: "Avalanche",
    logo: "A",
    balance: "15.25",
    value: "305.00",
    change: "+2.8%",
  },
  {
    id: "10",
    symbol: "DOT",
    name: "Polkadot",
    logo: "•",
    balance: "10.0",
    value: "65.00",
    change: "+1.8%",
  },
  {
    id: "11",
    symbol: "LINK",
    name: "Chainlink",
    logo: "L",
    balance: "20.0",
    value: "240.00",
    change: "+3.5%",
  },
  {
    id: "12",
    symbol: "UNI",
    name: "Uniswap",
    logo: "U",
    balance: "15.0",
    value: "75.00",
    change: "-2.1%",
  },
  {
    id: "13",
    symbol: "AAVE",
    name: "Aave",
    logo: "A",
    balance: "2.5",
    value: "175.00",
    change: "+1.3%",
  },
  {
    id: "14",
    symbol: "SHIB",
    name: "Shiba Inu",
    logo: "S",
    balance: "15000000",
    value: "150.00",
    change: "-5.2%",
  },
  {
    id: "15",
    symbol: "ADA",
    name: "Cardano",
    logo: "A",
    balance: "150.5",
    value: "75.25",
    change: "-3.2%",
  },
];
